export const CATEGORIES = [
  { name: 'Finance', slug: 'finance' },
  { name: 'Health', slug: 'health' },
  { name: 'Education', slug: 'education' },
  { name: 'Entertainment', slug: 'entertainment' },
  { name: 'Travel', slug: 'travel' },
  { name: 'Food', slug: 'food' },
  { name: 'Shopping', slug: 'shopping' },
  { name: 'Utilities', slug: 'utilities' },
  { name: 'Social', slug: 'social' },
  { name: 'News', slug: 'news' },
  { name: 'Sports', slug: 'sports' },
  { name: 'Weather', slug: 'weather' }
]

export const TAGS = [
  { name: 'Forms', slug: 'forms' },
  { name: 'Tables', slug: 'tables' },
  { name: 'Cards', slug: 'cards' },
  { name: 'Modals', slug: 'modals' },
  { name: 'Dropdowns', slug: 'dropdowns' },
  { name: 'Accordions', slug: 'accordions' },
  { name: 'Carousels', slug: 'carousels' },
  { name: 'Tabs', slug: 'tabs' },
  { name: 'Tooltips', slug: 'tooltips' },
  { name: 'Buttons', slug: 'buttons' },
  { name: 'Icons', slug: 'icons' },
  { name: 'Images', slug: 'images' },
  { name: 'Videos', slug: 'videos' },
  { name: 'Audio', slug: 'audio' },
  { name: 'Maps', slug: 'maps' },
  { name: 'Charts', slug: 'charts' },
  { name: 'Grids', slug: 'grids' },
  { name: 'Lists', slug: 'lists' },
  { name: 'Menus', slug: 'menus' },
  { name: 'Pagination', slug: 'pagination' },
  { name: 'Progress', slug: 'progress' },
  { name: 'Search', slug: 'search' },
  { name: 'Select', slug: 'select' },
  { name: 'Sliders', slug: 'sliders' },
  { name: 'Spinners', slug: 'spinners' },
  { name: 'Tags', slug: 'tags' },
  { name: 'Timelines', slug: 'timelines' },
  { name: 'Toasts', slug: 'toasts' },
  { name: 'Toolbars', slug: 'toolbars' },
  { name: 'Typography', slug: 'typography' },
  { name: 'Utils', slug: 'utils' },
  { name: 'Wrappers', slug: 'wrappers' }
]
